Update CICD (#13)

diff --git a/bin/dev-set b/bin/dev-set
--- a/bin/dev-set
+++ b/bin/dev-set
@@ -3,7 +3,7 @@
 # Set development environment variables
 #
 # * Source this script from the project's root directory
-# * Template Version: 6.0.0
+# * Template Version: 7.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -22,18 +22,24 @@
 #######################################
 
 #
+# Globals
+#
+
+export DEV_SET_VERBOSE="${DEV_SET_VERBOSE:-verbose}"
+
+#
 # Functions
 #
 
 function dev_set_error() {
   local msg="$1"
-  echo "Error: ${msg}"
+  echo "dev-set:Error: ${msg}"
   return 0
 }
 
 function dev_set_message() {
   local msg="$1"
-  [[ "$_DEV_SET_VERBOSE" == 'verbose' ]] && echo "$msg"
+  [[ "$DEV_SET_VERBOSE" == 'verbose' ]] && echo "dev-set: ${msg}"
   return 0
 }
 
@@ -67,19 +73,19 @@ function dev_set_load_gitlab() {
 }
 
 function dev_set_load_github() {
-  local dot_secrets='.secrets-github'
+  local dot_local='.local-github'
 
   dev_set_message "GitHub detected, setting project root (${GITHUB_WORKSPACE})"
   # shellcheck disable=SC2155
   export DEVCNT_ROOT="$GITHUB_WORKSPACE"
 
-  dot_secrets="${DEVCNT_ROOT}/${dot_secrets}"
-  if [[ -f "$dot_secrets" ]]; then
-    dev_set_message "Load github secrets (${dot_secrets})"
+  dot_local="${DEVCNT_ROOT}/${dot_local}"
+  if [[ -f "$dot_local" ]]; then
+    dev_set_message "Load local github automatic environment variables (${dot_local})"
     # shellcheck source=SCRIPTDIR/../.secrets-github
-    source "${dot_secrets}" ||
+    source "${dot_local}" ||
       {
-        dev_set_error "unable to source file (${dot_secrets})"
+        dev_set_error "unable to source file (${dot_local})"
         return 1
       }
   fi
@@ -115,8 +121,6 @@ function dev_set_load_env() {
 #
 # Main
 #
-
-declare _DEV_SET_VERBOSE="${1:-no}"
 
 # shellcheck disable=SC2154
 if [[ -f ./.local ]]; then
