dev: upgrade devbin64

diff --git a/bin/dev-lib-bashlib64 b/bin/dev-lib-bashlib64
--- a/bin/dev-lib-bashlib64
+++ b/bin/dev-lib-bashlib64
@@ -2,7 +2,7 @@
 #######################################
 # Dev / Lib / Bashlib64 / Download
 #
-# * Version: 4.1.0
+# * Version: 4.3.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -26,15 +26,15 @@
 
 # shellcheck source=bin/dev-set
 source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source=bin/dev-env-installer64
+source ./bin/dev-env-installer64 || exit 1
+# shellcheck source=bin/dev-env-bashlib64
+source ./bin/dev-env-bashlib64 || exit 1
 
 #
 # Globals
 #
 
-# CICD / Debug flag for bin/ scripts. Set to YES to enable
-export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
-# Lib / BashLib64 / Target
-export DEV_LIB_BASHLIB64_TARGET="${DEV_LIB_BASHLIB64_TARGET:-${DEV_PATH_LIB}/bl64}"
 # Lib / BashLib64 / Installer64 parameters
 export INST64_BASHLIB64_TARGET="$DEV_LIB_BASHLIB64_TARGET"
 
@@ -43,7 +43,15 @@ export INST64_BASHLIB64_TARGET="$DEV_LIB_BASHLIB64_TARGET"
 #
 
 [[ -n "$DEV_CICD_DEBUG" ]] && set -x
-[[ ! -d "$DEV_LIB_INSTALLER64_TARGET" ]] && dev_set_error 'Installer64 not found, please run ./bin/dev-lib-installer64 and try again' && exit 1
+[[ ! -d "$DEV_LIB_INSTALLER64_TARGET" ]] &&
+    echo 'dev-lib-installer64: Error: Installer64 not found, please run ./bin/dev-lib-installer64 and try again' &&
+    exit 1
 
+echo 'dev-lib-bashlib64: Task: remove BashLib64 older versions'
 [[ -d "$DEV_LIB_BASHLIB64_TARGET" ]] && rm -Rf "$DEV_LIB_BASHLIB64_TARGET"
-"${DEV_LIB_INSTALLER64_TARGET}/install-bashlib64"
+
+echo 'dev-lib-bashlib64: Task: download Installer64'
+"${DEV_LIB_INSTALLER64_TARGET}/install-bashlib64" &&
+    rm -f \
+        "${DEV_LIB_BASHLIB64_TARGET}/bashlib64.bash" \
+        "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-opt.bash"
