refact: migrate to devbin64 (#70)

diff --git a/bin/dev-auth-container b/bin/dev-auth-container
--- a/bin/dev-auth-container
+++ b/bin/dev-auth-container
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Authentication for dev-time resources
+# Dev / Auth / Container / Registry Login
 #
-# * Template: 1.0.0
+# * Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,10 +25,30 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source-path=lib/bl64
-source "${DEV_CICD_BASHLIB64}/bashlib64-module-cnt.bash" &&
-  source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-cnt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Auth / Docker / User
+DEV_AUTH_DOCKER_USER="${DEV_AUTH_DOCKER_USER:-}"
+export DEV_AUTH_DOCKER_USER
+DEV_AUTH_DOCKER_PASSWORD="${DEV_AUTH_DOCKER_PASSWORD:-}"
+export DEV_AUTH_DOCKER_PASSWORD
+# Auth / Docker / Registry
+DEV_AUTH_DOCKER_REGISTRY="${DEV_AUTH_DOCKER_REGISTRY:-}"
+export DEV_AUTH_DOCKER_REGISTRY
+# Auth / Docker / Registry Type
+DEV_AUTH_DOCKER_TYPE="${DEV_AUTH_DOCKER_TYPE:-GITHUB}"
+export DEV_AUTH_DOCKER_TYPE
+# Lib / GitHub / Command
+export DEV_LIB_GITHUB_BIN="${DEV_LIB_GITHUB_BIN:-/usr/bin/gh}"
 
 #
 # Functions
@@ -37,7 +57,7 @@ source "${DEV_CICD_BASHLIB64}/bashlib64-module-cnt.bash" &&
 function dev_auth_docker_ghtoken() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'Docker login with GitHub token'
-  "$DEV_LIB_GH_BIN" auth token |
+  "$DEV_LIB_GITHUB_BIN" auth token |
     bl64_cnt_login_stdin \
       "$DEV_AUTH_DOCKER_USER" "$DEV_AUTH_DOCKER_REGISTRY"
 }
@@ -57,27 +77,29 @@ function dev_auth_docker() {
   esac
 }
 
+function dev_auth_initialize() {
+  bl64_check_export 'DEV_AUTH_DOCKER_USER' &&
+    bl64_check_export 'DEV_AUTH_DOCKER_REGISTRY' &&
+    bl64_cnt_setup || return $?
+
+  if [[ "$DEV_AUTH_DOCKER_TYPE" == 'GITHUB' ]]; then
+    bl64_check_command_search_path "$DEV_LIB_GITHUB_BIN" ||
+      return $?
+  else
+    bl64_check_export 'DEV_AUTH_DOCKER_PASSWORD' ||
+      return $?
+  fi
+  return 0
+}
+
 #
 # Main
 #
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-
-bl64_check_export 'DEV_AUTH_DOCKER_USER' &&
-  bl64_check_export 'DEV_AUTH_DOCKER_REGISTRY' &&
-  bl64_check_export 'DEV_AUTH_DOCKER_TYPE' &&
-  bl64_cnt_setup || exit $?
-
-if [[ "$DEV_AUTH_DOCKER_TYPE" == 'GITHUB' ]]; then
-  bl64_check_export 'DEV_LIB_GH_BIN' &&
-    bl64_check_command_search_path "$DEV_LIB_GH_BIN" ||
-    exit $?
-else
-  bl64_check_export 'DEV_AUTH_DOCKER_PASSWORD' ||
-    exit $?
-fi
+dev_auth_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'auth-docker'
+bl64_msg_show_batch_start 'dev-auth-container'
 dev_auth_docker
-bl64_msg_show_batch_finish $? 'auth-docker'
+bl64_msg_show_batch_finish $? 'dev-auth-container'
diff --git a/bin/dev-auth-cosign b/bin/dev-auth-cosign
--- a/bin/dev-auth-cosign
+++ b/bin/dev-auth-cosign
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Authentication for dev-time resources
+# Dev / Auth / Cosign / Login
 #
-# * Template: 1.0.0
+# * Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,10 +25,26 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source-path=lib/bl64
-source "${DEV_CICD_BASHLIB64}/bashlib64-module-cnt.bash" &&
-  source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-cnt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Lib / Cosign / Command
+export DEV_LIB_COSIGN_BIN="${DEV_LIB_COSIGN_BIN:-/usr/local/bin/cosign}"
+# Lib / GitHub / Command
+export DEV_LIB_GITHUB_BIN="${DEV_LIB_GITHUB_BIN:-/usr/bin/gh}"
+# Auth / Cosign / Server
+export DEV_AUTH_COSIGN_SERVER="${DEV_AUTH_COSIGN_SERVER:-}"
+# Auth / Cosign / Server Type
+export DEV_AUTH_COSIGN_TYPE="${DEV_AUTH_COSIGN_TYPE:-GITHUB}"
+# Auth / Cosign / Server User
+export DEV_AUTH_COSIGN_USER="${DEV_AUTH_COSIGN_USER:-}"
+export DEV_AUTH_COSIGN_PASSWORD="${DEV_AUTH_COSIGN_PASSWORD:-}"
 
 #
 # Functions
@@ -38,7 +54,7 @@ function dev_auth_cosign_ghtoken() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'Cosign login with GitHub token'
   bl64_dbg_app_trace_start
-  "$DEV_LIB_GH_BIN" \
+  "$DEV_LIB_GITHUB_BIN" \
     auth token |
     "$DEV_LIB_COSIGN_BIN" \
       login \
@@ -68,29 +84,31 @@ function dev_auth_cosign() {
   esac
 }
 
+function dev_auth_initialize() {
+  bl64_dbg_app_show_function
+  bl64_check_export 'DEV_AUTH_COSIGN_USER' &&
+    bl64_check_export 'DEV_AUTH_COSIGN_SERVER' &&
+    bl64_check_command_search_path "$DEV_LIB_COSIGN_BIN" ||
+    return $?
+
+  if [[ "$DEV_AUTH_COSIGN_TYPE" == 'GITHUB' ]]; then
+    bl64_check_command_search_path "$DEV_LIB_GITHUB_BIN" ||
+      return $?
+  else
+    bl64_check_export 'DEV_AUTH_COSIGN_PASSWORD' ||
+      return $?
+  fi
+  return 0
+}
+
 #
 # Main
 #
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-
-bl64_check_export 'DEV_AUTH_COSIGN_USER' &&
-  bl64_check_export 'DEV_AUTH_COSIGN_SERVER' &&
-  bl64_check_export 'DEV_AUTH_COSIGN_TYPE' &&
-  bl64_check_export 'DEV_LIB_COSIGN_BIN' &&
-  bl64_check_command_search_path "$DEV_LIB_COSIGN_BIN" ||
-  exit $?
-
-if [[ "$DEV_AUTH_COSIGN_TYPE" == 'GITHUB' ]]; then
-  bl64_check_export 'DEV_LIB_GH_BIN' &&
-    bl64_check_command_search_path "$DEV_LIB_GH_BIN" ||
-    exit $?
-else
-  bl64_check_export 'DEV_AUTH_COSIGN_PASSWORD' ||
-    exit $?
-fi
+dev_auth_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'auth-cosign'
+bl64_msg_show_batch_start 'dev-auth-cosign'
 dev_auth_cosign
-bl64_msg_show_batch_finish $? 'auth-cosign'
+bl64_msg_show_batch_finish $? 'dev-auth-cosign'
diff --git a/bin/dev-auth-github b/bin/dev-auth-github
--- a/bin/dev-auth-github
+++ b/bin/dev-auth-github
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Authentication for dev-time resources
+# Dev / Auth / GitHug / Login
 #
-# * Template: 1.0.0
+# * Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,9 +25,22 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source-path=lib/bl64
-source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Lib / GitHub / Command
+export DEV_LIB_GITHUB_BIN="${DEV_LIB_GITHUB_BIN:-/usr/bin/gh}"
+# Auth / GitHub / Scopes
+export DEV_AUTH_GITHUB_SCOPES="${DEV_AUTH_GITHUB_SCOPES:-}"
+# Auth / GitHub / Token
+export GITHUB_TOKEN="${GITHUB_TOKEN:-}"
 
 #
 # Functions
@@ -35,9 +48,16 @@ source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
 
 function dev_auth_github() {
   bl64_dbg_app_show_function
-  "$DEV_LIB_GH_BIN" \
+  [[ -z "$GITHUB_TOKEN" ]] && bl64_msg_show_warning 'variable GITHUB_TOKEN is unset, using interactive login'
+  "$DEV_LIB_GITHUB_BIN" \
     auth login \
-    --scopes "$DEV_AUTH_GH_SCOPES"
+    --scopes "$DEV_AUTH_GITHUB_SCOPES"
+}
+
+function dev_auth_initialize() {
+  bl64_dbg_app_show_function
+  bl64_check_command_search_path "$DEV_LIB_GITHUB_BIN" ||
+    return $?
 }
 
 #
@@ -45,11 +65,9 @@ function dev_auth_github() {
 #
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-bl64_check_export 'DEV_LIB_GH_BIN' &&
-  bl64_check_command_search_path "$DEV_LIB_GH_BIN" ||
-  exit $?
+dev_auth_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'auth-github'
+bl64_msg_show_batch_start 'dev-auth-github'
 dev_auth_github
-bl64_msg_show_batch_finish $? 'auth-github'
+bl64_msg_show_batch_finish $? 'dev-auth-github'
diff --git a/bin/dev-git-branch-close b/bin/dev-git-branch-close
--- a/bin/dev-git-branch-close
+++ b/bin/dev-git-branch-close
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Close branch
+# Dev / GIT / Close branch
 #
-# * Template: 1.1.0
+# * Version: 2.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,9 +25,18 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# GIT / Main branch name
+export DEV_GIT_BRANCH_MAIN="${DEV_GIT_BRANCH_MAIN:-main}"
 
 #
 # Functions
@@ -36,10 +45,15 @@ source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
 function dev_repo_branch_close() {
   bl64_dbg_app_show_function "$@"
   local dev_repo_branch_name="$1"
-  bl64_msg_show_task "switch to main branch (${DEV_CICD_BRANCH_MAIN})" &&
-    bl64_vcs_run_git checkout "$DEV_CICD_BRANCH_MAIN" &&
+  bl64_msg_show_task "switch to main branch (${DEV_GIT_BRANCH_MAIN})" &&
+    bl64_vcs_run_git checkout "$DEV_GIT_BRANCH_MAIN" &&
     bl64_msg_show_task "delete local branch (${dev_repo_branch_name})" &&
     bl64_vcs_run_git branch -d "$dev_repo_branch_name"
+}
+
+function dev_git_initialize() {
+  bl64_dbg_app_show_function
+  bl64_vcs_setup
 }
 
 #
@@ -49,13 +63,9 @@ function dev_repo_branch_close() {
 declare dev_repo_branch_name="${1:-feature/update}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-
-bl64_check_export 'DEV_CICD_BRANCH_MAIN' &&
-  bl64_check_parameter 'dev_repo_branch_name' &&
-  bl64_vcs_setup ||
-  exit $?
+dev_git_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'repo-branch-close'
+bl64_msg_show_batch_start 'dev-git-branch-close'
 dev_repo_branch_close "$dev_repo_branch_name"
-bl64_msg_show_batch_finish $? 'repo-branch-close'
+bl64_msg_show_batch_finish $? 'dev-git-branch-close'
diff --git a/bin/dev-git-branch-create b/bin/dev-git-branch-create
--- a/bin/dev-git-branch-create
+++ b/bin/dev-git-branch-create
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Create branch from main
+# Dev / GIT / Create branch from main
 #
-# * Template: 2.1.0
+# * Version: 3.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,9 +25,20 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# GIT / Main branch name
+export DEV_GIT_BRANCH_MAIN="${DEV_GIT_BRANCH_MAIN:-main}"
+# GIT / Origin remote name
+export DEV_GIT_REMOTE_ORIGIN="${DEV_GIT_REMOTE_ORIGIN:-origin}"
 
 #
 # Functions
@@ -37,12 +48,17 @@ function dev_repo_branch_create() {
   bl64_dbg_app_show_function "$@"
   local dev_repo_branch_name="$1"
 
-  bl64_msg_show_task "switch to main branch (${DEV_CICD_BRANCH_MAIN})"
-  bl64_vcs_run_git checkout "$DEV_CICD_BRANCH_MAIN" &&
+  bl64_msg_show_task "switch to main branch (${DEV_GIT_BRANCH_MAIN})"
+  bl64_vcs_run_git checkout "$DEV_GIT_BRANCH_MAIN" &&
     bl64_msg_show_task "create branch (${dev_repo_branch_name})" &&
     bl64_vcs_run_git checkout -b "$dev_repo_branch_name" &&
-    bl64_msg_show_task "register branch in origin (${DEV_CICD_REPO_ORIGIN_NAME}/${dev_repo_branch_name})" &&
-    bl64_vcs_run_git push --set-upstream "${DEV_CICD_REPO_ORIGIN_NAME}" "${dev_repo_branch_name}"
+    bl64_msg_show_task "register branch in origin (${DEV_GIT_REMOTE_ORIGIN}/${dev_repo_branch_name})" &&
+    bl64_vcs_run_git push --set-upstream "${DEV_GIT_REMOTE_ORIGIN}" "${dev_repo_branch_name}"
+}
+
+function dev_git_initialize() {
+  bl64_dbg_app_show_function
+  bl64_vcs_setup
 }
 
 #
@@ -52,14 +68,9 @@ function dev_repo_branch_create() {
 declare dev_repo_branch_name="${1:-feature/update}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-
-bl64_check_export 'DEV_CICD_BRANCH_MAIN' &&
-  bl64_check_export 'DEV_CICD_REPO_ORIGIN_NAME' &&
-  bl64_check_parameter 'dev_repo_branch_name' &&
-  bl64_vcs_setup ||
-  exit $?
+dev_git_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'repo-branch-create'
+bl64_msg_show_batch_start 'dev-git-branch-create'
 dev_repo_branch_create "$dev_repo_branch_name"
-bl64_msg_show_batch_finish $? 'repo-branch-create'
+bl64_msg_show_batch_finish $? 'dev-git-branch-create'
diff --git a/bin/dev-git-repo-duplicate b/bin/dev-git-repo-duplicate
--- a/bin/dev-git-repo-duplicate
+++ b/bin/dev-git-repo-duplicate
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 #######################################
-# Duplicate content from one GIT repository to other
+# Dev / GIT / Duplicate content from one GIT repository to other
 #
 # * Both repositories are independant from each other: they don't share the same origin
 # * Duplication will add and remove files from destination as needed
 # * Excluded from duplication: GIT metadata (.git) and temporary locations (tmp, lib)
 # * Operation is done using rsync tool
-# * Template: 3.0.0
+# * Version: 3.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,32 +29,41 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source=lib/bl64/bashlib64-core.bash
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Lib / RSync / Command
+export DEV_LIB_RSYNC_BIN="${DEV_LIB_RSYNC_BIN:-/usr/bin/rsync}"
 
 #
 # Functions
 #
 
-function dev_repo_duplicate() {
+function dev_git_repo_duplicate() {
   bl64_dbg_app_show_function "$@"
-  local dev_repo_destination="$1"
-  local dev_repo_dry_run="$2"
-  local dev_repo_source=''
+  local dev_git_destination="$1"
+  local dev_git_dry_run="$2"
+  local dev_git_source=''
 
-  dev_repo_source="$(pwd)/"
-  bl64_msg_show_task "duplicate repositories (${dev_repo_source}->${dev_repo_destination})"
-  if [[ -z "$dev_repo_dry_run" ]]; then
+  dev_git_source="$(pwd)/"
+  bl64_msg_show_task "duplicate repositories (${dev_git_source}->${dev_git_destination})"
+  if [[ -z "$dev_git_dry_run" ]]; then
     bl64_msg_show_warning 'using dry-run mode. No action will be performed. Set the 2nd parameter to OFF to perform the action'
-    dev_repo_dry_run='--dry-run'
+    dev_git_dry_run='--dry-run'
   else
-    [[ -n "$dev_repo_dry_run" ]] && dev_repo_dry_run=''
+    [[ -n "$dev_git_dry_run" ]] && dev_git_dry_run=''
   fi
 
   # shellcheck disable=SC2086
   "$DEV_LIB_RSYNC_BIN" \
-    ${dev_repo_dry_run} \
+    ${dev_git_dry_run} \
     --one-file-system \
     --human-readable \
     --progress \
@@ -71,26 +80,28 @@ function dev_repo_duplicate() {
     --exclude='.git/' \
     --exclude='tmp/' \
     --exclude='lib/' \
-    --exclude='var/fluxcd/' \
-    "$dev_repo_source" \
-    "${dev_repo_destination}/"
+    "$dev_git_source" \
+    "${dev_git_destination}/"
+}
+
+function dev_git_initialize() {
+  bl64_dbg_app_show_function
+  bl64_check_command_search_path "$DEV_LIB_RSYNC_BIN" &&
+    bl64_check_parameter 'dev_git_destination' &&
+    bl64_check_directory "$dev_git_destination"
 }
 
 #
 # Main
 #
 
-declare dev_repo_destination="${1:-}"
-declare dev_repo_dry_run="${2:-}"
+declare dev_git_destination="${1:-}"
+declare dev_git_dry_run="${2:-}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-bl64_check_export 'DEV_LIB_RSYNC_BIN' &&
-  bl64_check_command_search_path "$DEV_LIB_RSYNC_BIN" &&
-  bl64_check_parameter 'dev_repo_destination' &&
-  bl64_check_directory "$dev_repo_destination" ||
-  exit $?
+dev_git_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'repo-duplicate'
-dev_repo_duplicate "$dev_repo_destination" "$dev_repo_dry_run"
-bl64_msg_show_batch_finish $? 'repo-duplicate'
+bl64_msg_show_batch_start 'dev-git-repo-duplicate'
+dev_git_repo_duplicate "$dev_git_destination" "$dev_git_dry_run"
+bl64_msg_show_batch_finish $? 'dev-git-repo-duplicate'
diff --git a/bin/dev-git-tag-create b/bin/dev-git-tag-create
--- a/bin/dev-git-tag-create
+++ b/bin/dev-git-tag-create
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 #######################################
-# Create and push GIT tag
+# Dev / GIT / Create and push GIT tag
 #
-# * Main branch only
-# * Template: 1.1.0
+# * Works on the main branch
+# * Version: 2.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -26,9 +26,24 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source=lib/bl64/bashlib64-core.bash
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Dev / Changelog
+export DEV_CICD_CHANGELOG="${DEV_CICD_CHANGELOG:-CHANGELOG.md}"0
+# GIT / Main branch name
+export DEV_GIT_BRANCH_MAIN="${DEV_GIT_BRANCH_MAIN:-main}"
+# GIT / Origin remote name
+export DEV_GIT_REMOTE_ORIGIN="${DEV_GIT_REMOTE_ORIGIN:-origin}"
+# GIT / Upstream remote name
+export DEV_GIT_REMOTE_UPSTREAM="${DEV_GIT_REMOTE_UPSTREAM:-upstream}"
 
 #
 # Functions
@@ -55,18 +70,18 @@ function dev_repo_get_changes() {
     print $0
     next
   }
-  ' "$DEV_CICD_REPO_CHANGELOG"
+  ' "$DEV_CICD_CHANGELOG"
 }
 
-function dev_repo_tag() {
+function dev_git_tag_create() {
   bl64_dbg_app_show_function "$@"
   local new_tag="$1"
   local include_changelog="$2"
   local message=''
   local -i status=0
 
-  bl64_msg_show_task "switch to main branch (${DEV_CICD_BRANCH_MAIN})"
-  bl64_vcs_run_git checkout "$DEV_CICD_BRANCH_MAIN" ||
+  bl64_msg_show_task "switch to main branch (${DEV_GIT_BRANCH_MAIN})"
+  bl64_vcs_run_git checkout "$DEV_GIT_BRANCH_MAIN" ||
     return $?
 
   bl64_msg_show_task "create tag (${new_tag})"
@@ -82,14 +97,21 @@ function dev_repo_tag() {
       return $?
   fi
 
-  bl64_msg_show_task "push tag to origin (${DEV_CICD_REPO_ORIGIN_NAME})"
-  bl64_vcs_run_git push "$DEV_CICD_REPO_ORIGIN_NAME" "$new_tag" ||
+  bl64_msg_show_task "push tag to origin (${DEV_GIT_REMOTE_ORIGIN})"
+  bl64_vcs_run_git push "$DEV_GIT_REMOTE_ORIGIN" "$new_tag" ||
     return $?
 
-  if [[ -n "$DEV_CICD_REPO_UPSTREAM_NAME" ]]; then
-    bl64_msg_show_task "push tag to upstream (${DEV_CICD_REPO_UPSTREAM_NAME})"
-    bl64_vcs_run_git push "$DEV_CICD_REPO_UPSTREAM_NAME" "$new_tag"
+  if [[ -n "$DEV_GIT_REMOTE_UPSTREAM" ]]; then
+    bl64_msg_show_task "push tag to upstream (${DEV_GIT_REMOTE_UPSTREAM})"
+    bl64_vcs_run_git push "$DEV_GIT_REMOTE_UPSTREAM" "$new_tag"
   fi
+}
+
+function dev_git_initialize() {
+  bl64_dbg_app_show_function "$@"
+  local dev_repo_new_tag="$1"
+  bl64_check_parameter 'dev_repo_new_tag' &&
+    bl64_vcs_setup
 }
 
 #
@@ -100,14 +122,9 @@ declare dev_repo_new_tag="${1:-}"
 declare dev_repo_include_changelog="${2:-$BL64_VAR_OFF}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-
-bl64_check_parameter 'dev_repo_new_tag' &&
-  bl64_check_export 'DEV_CICD_BRANCH_MAIN' &&
-  bl64_check_export 'DEV_CICD_REPO_ORIGIN_NAME' &&
-  bl64_vcs_setup ||
-  exit $?
+dev_git_initialize "$dev_repo_new_tag" || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'repo-tag'
-dev_repo_tag "$dev_repo_new_tag" "$dev_repo_include_changelog"
-bl64_msg_show_batch_finish $? 'repo-tag'
+bl64_msg_show_batch_start 'dev-git-tag-create'
+dev_git_tag_create "$dev_repo_new_tag" "$dev_repo_include_changelog"
+bl64_msg_show_batch_finish $? 'dev-git-tag-create'
diff --git a/bin/dev-lab-container b/bin/dev-lab-container
--- a/bin/dev-lab-container
+++ b/bin/dev-lab-container
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Open sandbox environment
+# Dev / Lab / Open sandbox environment
 #
-# * Template: 1.4.0
+# * Version: 1.5.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,9 +25,23 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=lib/bl64
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-cnt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Lab / Container Registry
+DEV_LAB_REGISTRY="${DEV_LAB_REGISTRY:-ghcr.io/automation64}"
+export DEV_LAB_REGISTRY
+# Lab / Default image
+DEV_LAB_IMAGE="${DEV_LAB_IMAGE:-base/alpine-3-base}"
+export DEV_LAB_IMAGE
 
 #
 # Functions
@@ -44,24 +58,26 @@ function dev_lab_open() {
   bl64_cnt_run_interactive \
     --entrypoint="$dev_lab_entrypoint" \
     --workdir="$dev_lab_path_project" \
-    --mount "type=bind,source=${DEV_SRC},target=${dev_lab_path_source},readonly" \
-    --mount "type=bind,source=${DEV_ROOT},target=${dev_lab_path_project},readonly" \
-    "${DEV_CICD_LAB_REGISTRY}/${dev_lab_image}"
+    --mount "type=bind,source=${DEV_PATH_SRC},target=${dev_lab_path_source},readonly" \
+    --mount "type=bind,source=${DEV_PATH_ROOT},target=${dev_lab_path_project},readonly" \
+    "${DEV_LAB_REGISTRY}/${dev_lab_image}"
+}
+
+function dev_lab_initialize() {
+  bl64_dbg_app_show_function
+  bl64_cnt_setup
 }
 
 #
 # Main
 #
 
-declare dev_lab_image="${1:-$DEV_CICD_LAB_IMAGE}"
+declare dev_lab_image="${1:-$DEV_LAB_IMAGE}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-bl64_check_parameter 'dev_lab_image' &&
-  bl64_check_export 'DEV_CICD_LAB_REGISTRY' &&
-  bl64_cnt_setup ||
-  exit $?
-
+dev_lab_initialize || exit $?
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'lab'
+
+bl64_msg_show_batch_start 'dev-lab-container'
 dev_lab_open "$dev_lab_image"
-bl64_msg_show_batch_finish $? 'lab'
+bl64_msg_show_batch_finish $? 'dev-lab-container'
diff --git a/bin/dev-lib-bashlib64 b/bin/dev-lib-bashlib64
--- a/bin/dev-lib-bashlib64
+++ b/bin/dev-lib-bashlib64
@@ -1,24 +1,48 @@
 #!/usr/bin/env bash
+#######################################
+# Dev / Lib / Bashlib64 / Download
 #
-# Update dev-time external tool: BashLib64
+# * Version: 4.0.0
 #
-# * Template: 3.0.0
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
 #
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
 
 #
 # Imports
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Lib / BashLib64 / Target
+export DEV_LIB_BASHLIB64_TARGET="${DEV_LIB_BASHLIB64_TARGET:-${DEV_PATH_LIB}/bl64}"
+export INST64_BASHLIB64_TARGET="$DEV_LIB_BASHLIB64_TARGET"
 
 #
 # Main
 #
 
-[[ -z "$DEV_LIB_INSTALLER64_TARGET" ]] &&
-  echo 'error: Installer64 not found. Use the dev-lib-instaler64 script to deploy it)' &&
-  exit 1
+[[ -n "$DEV_CICD_DEBUG" ]] && set -x
+[[ ! -d "$DEV_LIB_INSTALLER64_TARGET" ]] && dev_set_error 'Installer64 not found, please run ./bin/dev-lib-installer64 and try again' && exit 1
 
-export INST64_BASHLIB64_TARGET="$DEV_CICD_BASHLIB64"
+[[ -d "$DEV_LIB_BASHLIB64_TARGET" ]] && rm -Rf "$DEV_LIB_BASHLIB64_TARGET"
 "${DEV_LIB_INSTALLER64_TARGET}/install-bashlib64"
