refact: upgrade bl64

diff --git a/cntbuild b/cntbuild
--- a/cntbuild
+++ b/cntbuild
@@ -1825,7 +1825,7 @@ function bl64_fmt_check_value_in_list() {
 
 # shellcheck disable=SC2034
 {
-  declare BL64_VCS_VERSION='2.1.0'
+  declare BL64_VCS_VERSION='2.2.0'
 
   declare BL64_VCS_MODULE='0'
 
@@ -2031,7 +2031,8 @@ function bl64_vcs_blank_git() {
 # Arguments:
 #   $1: URL to the GIT repository
 #   $2: destination path where the repository will be created
-#   $3: branch name. Default: main
+#   $3: (optional) branch name
+#   $4: (optional) new repository name
 # Outputs:
 #   STDOUT: git output
 #   STDERR: git stderr
@@ -2042,27 +2043,35 @@ function bl64_vcs_git_clone() {
   bl64_dbg_lib_show_function "$@"
   local source="${1}"
   local destination="${2}"
-  local branch="${3:-main}"
+  local branch="${3:-$BL64_VAR_DEFAULT}"
+  local name="${4:-$BL64_VAR_DEFAULT}"
 
+  [[ "$branch" == "$BL64_VAR_DEFAULT" ]] && branch=''
   bl64_check_parameter 'source' &&
     bl64_check_parameter 'destination' &&
     bl64_check_command "$BL64_VCS_CMD_GIT" ||
     return $?
 
-  bl64_fs_create_dir "${BL64_VAR_DEFAULT}" "${BL64_VAR_DEFAULT}" "${BL64_VAR_DEFAULT}" "$destination" || return $?
+  bl64_msg_show_lib_subtask "$_BL64_VCS_TXT_CLONE_REPO (${source} -> ${destination})"
+  bl64_fs_create_dir "${BL64_VAR_DEFAULT}" "${BL64_VAR_DEFAULT}" "${BL64_VAR_DEFAULT}" "$destination" &&
+    cd "$destination" ||
+    return $?
 
-  bl64_msg_show_lib_subtask "$_BL64_VCS_TXT_CLONE_REPO ($source)"
-
-  # shellcheck disable=SC2164
-  cd "$destination"
-
-  # shellcheck disable=SC2086
-  bl64_vcs_run_git \
-    clone \
-    --depth 1 \
-    --single-branch \
-    --branch "$branch" \
-    "$source"
+  if [[ "$name" == "$BL64_VAR_DEFAULT" ]]; then
+    bl64_vcs_run_git \
+      clone \
+      --depth 1 \
+      --single-branch \
+      ${branch:+--branch $branch} \
+      "$source"
+  else
+    bl64_vcs_run_git \
+      clone \
+      --depth 1 \
+      --single-branch \
+      ${branch:+--branch $branch} \
+      "$source" "$name"
+  fi
 }
 
 #######################################
@@ -2232,6 +2241,69 @@ function _bl64_vcs_github_release_get_latest() {
       '/"tag_name": "/ {
         gsub(/[ ",]/,"", $2); print $2
       }'
+}
+
+#######################################
+# Changelog / Get release description for a semver tag
+#
+# * Uses standard Changelog format
+# * Uses standard semver tag
+#
+# Arguments:
+#   $1: changelog path
+#   $2: semver release tag
+# Outputs:
+#   STDOUT: release description
+#   STDERR: execution error
+# Returns:
+#   0: release description found
+#   >0: unable to get release description
+#######################################
+function bl64_vcs_changelog_get_release() {
+  bl64_dbg_lib_show_function "$@"
+  local changelog_path="$1"
+  local release_tag="$2"
+  local description=''
+
+  bl64_check_parameter 'changelog_path' &&
+    bl64_check_parameter 'release_tag' &&
+    bl64_check_file "$changelog_path" ||
+    return $?
+
+  description="$(
+    _bl64_vcs_changelog_get_release \
+      "$changelog_path" \
+      "$release_tag"
+  )" &&
+    [[ -n "$description" ]] &&
+    printf '%s' "$description"
+}
+
+function _bl64_vcs_changelog_get_release() {
+  bl64_dbg_lib_show_function "$@"
+  local changelog_path="$1"
+  local release_tag="$2"
+
+  bl64_txt_run_awk \
+    -v tag="$release_tag" '
+  BEGIN {
+      section = 0
+      pattern = "## \\[" tag "\\]"
+  }
+  /^$/ { next }
+  section == 0 && $0 ~ pattern {
+    section = 1
+    next
+  }
+  section == 1 && (/^## \[[0-9]+\.[0-9]\.+[0-9]+\]$/ || /^\[[0-9]+\.[0-9]\.+[0-9]+\]: /) {
+    exit
+  }
+  section == 1 {
+    gsub(/#/,"*")
+    print $0
+    next
+  }
+  ' "$changelog_path"
 }
 
 #!/usr/bin/env bash
@@ -3648,7 +3720,7 @@ function bl64_cnt_check_not_in_container() {
 
 # shellcheck disable=SC2034
 {
-  declare BL64_FS_VERSION='5.2.0'
+  declare BL64_FS_VERSION='5.3.1'
 
   declare BL64_FS_MODULE='0'
 
@@ -4092,10 +4164,11 @@ function _bl64_fs_set_alias() {
 #   $3: group name. Default: current
 #   $@: full directory paths
 # Outputs:
-#   STDOUT: command dependant
-#   STDERR: command dependant
+#   STDOUT: verbose operation
+#   STDOUT: command errors
 # Returns:
-#   command dependant
+#   0: Operation completed ok
+#   >0: Operation failed
 #######################################
 function bl64_fs_create_dir() {
   bl64_dbg_lib_show_function "$@"
@@ -4130,6 +4203,8 @@ function bl64_fs_create_dir() {
 #######################################
 # Copy one ore more files to a single destination, then set owner and permissions
 #
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_copy
+#
 # Requirements:
 #   * Destination path should be present
 #   * root privilege (sudo) if paths are restricted or change owner is requested
@@ -4142,10 +4217,11 @@ function bl64_fs_create_dir() {
 #   $4: destination path
 #   $@: full file paths
 # Outputs:
-#   STDOUT: command dependant
-#   STDERR: command dependant
+#   STDOUT: verbose operation
+#   STDOUT: command errors
 # Returns:
-#   command dependant
+#   0: Operation completed ok
+#   >0: Operation failed
 #######################################
 function bl64_fs_copy_files() {
   bl64_dbg_lib_show_function "$@"
@@ -4153,8 +4229,88 @@ function bl64_fs_copy_files() {
   local user="${2:-${BL64_VAR_DEFAULT}}"
   local group="${3:-${BL64_VAR_DEFAULT}}"
   local destination="${4:-${BL64_VAR_DEFAULT}}"
-  local path=''
-  local target=''
+
+  # Remove consumed parameters
+  shift
+  shift
+  shift
+  shift
+
+  bl64_fs_path_copy \
+    "$mode" \
+    "$BL64_VAR_DEFAULT" \
+    "$user" \
+    "$group" \
+    "$destination" \
+    "$@"
+}
+
+#######################################
+#  Remove paths (files, directories)
+#
+# * Recursive
+# * No error if the path is not present
+# * No backup previous to removal
+#
+# Arguments:
+#   $@: list of full file paths
+# Outputs:
+#   STDOUT: verbose operation
+#   STDOUT: command errors
+# Returns:
+#   0: Operation completed ok
+#   >0: Operation failed
+#######################################
+function bl64_fs_path_remove() {
+  bl64_dbg_lib_show_function "$@"
+  local path_current=''
+
+  bl64_check_parameters_none "$#" ||
+    return $?
+
+  for path_current in "$@"; do
+    [[ ! -e "$path_current" ]] && continue
+    bl64_msg_show_lib_subtask "remove path (${path_current})"
+    bl64_fs_run_rm \
+      "$BL64_FS_SET_RM_FORCE" \
+      "$BL64_FS_SET_RM_RECURSIVE" \
+      "$path_current" ||
+      return $?
+  done
+}
+
+#######################################
+# Copy one ore more paths to a single destination. Optinally set owner and permissions
+#
+# * Wildcards are not allowed. Use run_cp instead if needed
+# * Path can be directory and/or file only
+# * Destination path should be present
+# * Root privilege (sudo) needed if paths are restricted or change owner is requested
+# * No rollback in case of errors. The process will not remove already copied files
+#
+# Arguments:
+#   $1: file permissions. Format: chown format. Default: use current umask
+#   $2: directory permissions. Format: chown format. Default: use current umask
+#   $3: user name. Default: current
+#   $4: group name. Default: current
+#   $5: destination path
+#   $@: full source paths. No wildcards allowed
+# Outputs:
+#   STDOUT: verbose operation
+#   STDERR: command errors
+# Returns:
+#   0: Operation completed ok
+#   >0: Operation failed
+#######################################
+function bl64_fs_path_copy() {
+  bl64_dbg_lib_show_function "$@"
+  local file_mode="${1:-${BL64_VAR_DEFAULT}}"
+  local dir_mode="${2:-${BL64_VAR_DEFAULT}}"
+  local user="${3:-${BL64_VAR_DEFAULT}}"
+  local group="${4:-${BL64_VAR_DEFAULT}}"
+  local destination="${5:-${BL64_VAR_DEFAULT}}"
+  local path_current=''
+  local path_base=
 
   bl64_check_directory "$destination" || return $?
 
@@ -4163,22 +4319,29 @@ function bl64_fs_copy_files() {
   shift
   shift
   shift
+  shift
 
   # shellcheck disable=SC2086
   bl64_check_parameters_none "$#" || return $?
-  bl64_dbg_lib_show_info "paths:[${*}]"
-  for path in "$@"; do
-    target=''
-    bl64_check_path_absolute "$path" &&
-      target="${destination}/$(bl64_fmt_basename "$path")" || return $?
+  bl64_msg_show_lib_subtask "${_BL64_FS_TXT_COPY_FILE_PATH} (${*} ${BL64_MSG_COSMETIC_ARROW2} ${destination})"
+  # shellcheck disable=SC2086
+  bl64_fs_run_cp \
+    $BL64_FS_SET_CP_FORCE \
+    $BL64_FS_SET_CP_RECURSIVE \
+    "$@" \
+    "$destination" ||
+    return $?
 
-    bl64_msg_show_lib_subtask "${_BL64_FS_TXT_COPY_FILE_PATH} (${path} ${BL64_MSG_COSMETIC_ARROW2} ${target})"
-    bl64_fs_cp_file "$path" "$target" &&
-      bl64_fs_set_permissions "$mode" "$user" "$group" "$target" ||
+  for path_current in "$@"; do
+    path_base="$(bl64_fmt_basename "$path_current")"
+    bl64_fs_path_permission_set \
+      "$file_mode" \
+      "$dir_mode" \
+      "$user" \
+      "$group" \
+      "${destination}/${path_base}" ||
       return $?
   done
-
-  return 0
 }
 
 #######################################
@@ -4196,8 +4359,8 @@ function bl64_fs_copy_files() {
 #   $5: destination file. Full path
 #   $@: source files. Full path
 # Outputs:
-#   STDOUT: command dependant
-#   STDERR: command dependant
+#   STDOUT: verbose operation
+#   STDOUT: command errors
 # Returns:
 #   command dependant
 #   $BL64_FS_ERROR_EXISTING_FILE
@@ -4267,8 +4430,6 @@ function bl64_fs_merge_files() {
 #   STDOUT: command output
 #   STDERR: command stderr
 # Returns:
-#   bl64_check_parameter
-#   bl64_check_directory
 #   0: operation completed ok
 #   >0: operation failed
 #######################################
@@ -4433,6 +4594,7 @@ function bl64_fs_chmod_dir() {
 #######################################
 # Copy files with force flag
 #
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_copy
 # * Simple command wrapper
 #
 # Arguments:
@@ -4454,6 +4616,7 @@ function bl64_fs_cp_file() {
 #######################################
 # Copy directory with recursive and force flags
 #
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_copy
 # * Simple command wrapper
 #
 # Arguments:
@@ -4567,6 +4730,8 @@ function bl64_fs_run_mv() {
 #######################################
 # Remove files using the verbose and force flags. Limited to current filesystem
 #
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_remove
+#
 # Arguments:
 #   $@: arguments are passed as-is to the command
 # Outputs:
@@ -4578,14 +4743,13 @@ function bl64_fs_run_mv() {
 #######################################
 function bl64_fs_rm_file() {
   bl64_dbg_lib_show_function "$@"
-
-  bl64_check_parameters_none "$#" || return $?
-
-  bl64_fs_run_rm "$BL64_FS_SET_RM_FORCE" "$@"
+  bl64_fs_path_remove "$@"
 }
 
 #######################################
 # Remove directories using the verbose and force flags. Limited to current filesystem
+#
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_remove
 #
 # Arguments:
 #   $@: arguments are passed as-is to the command
@@ -4598,10 +4762,7 @@ function bl64_fs_rm_file() {
 #######################################
 function bl64_fs_rm_full() {
   bl64_dbg_lib_show_function "$@"
-
-  bl64_check_parameters_none "$#" || return $?
-
-  bl64_fs_run_rm "$BL64_FS_SET_RM_FORCE" "$BL64_FS_SET_RM_RECURSIVE" "$@"
+  bl64_fs_path_remove "$@"
 }
 
 #######################################
@@ -4874,13 +5035,14 @@ function bl64_fs_restore() {
 #######################################
 # Set object permissions and ownership
 #
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_permission_set
 # * work on individual files
 # * no recurse option
 # * all files get the same permissions, user, group
 #
 # Arguments:
 #   $1: permissions. Format: chown format. Default: use current umask
-#   $2: user name. Default: nonde
+#   $2: user name. Default: none
 #   $3: group name. Default: current
 #   $@: list of objects. Must use full path for each
 # Outputs:
@@ -4902,30 +5064,18 @@ function bl64_fs_set_permissions() {
   shift
   shift
 
-  bl64_check_parameters_none "$#" || return $?
-  bl64_dbg_lib_show_info "path list:[${*}]"
-
-  if [[ "$mode" != "$BL64_VAR_DEFAULT" ]]; then
-    bl64_msg_show_lib_subtask "${_BL64_FS_TXT_SET_MODE} (${mode} ${BL64_MSG_COSMETIC_ARROW2} ${*})"
-    bl64_fs_run_chmod "$mode" "$@" || return $?
-  fi
-
-  if [[ "$user" != "$BL64_VAR_DEFAULT" ]]; then
-    bl64_msg_show_lib_subtask "${_BL64_FS_TXT_SET_OWNER} (${user} ${BL64_MSG_COSMETIC_ARROW2} ${*})"
-    bl64_fs_run_chown "${user}" "$@" || return $?
-  fi
-
-  if [[ "$group" != "$BL64_VAR_DEFAULT" ]]; then
-    bl64_msg_show_lib_subtask "${_BL64_FS_TXT_SET_GROUP} (${group} ${BL64_MSG_COSMETIC_ARROW2} ${*})"
-    bl64_fs_run_chown ":${group}" "$@" || return $?
-  fi
-
-  return 0
+  bl64_fs_path_permission_set \
+    "$mode" \
+    "$BL64_VAR_DEFAULT" \
+    "$user" \
+    "$group" \
+    "$@"
 }
 
 #######################################
 # Fix path permissions
 #
+# * TODO: to be removed in future versions. Migrate to bl64_fs_path_permission_set
 # * allow different permissions for files and directories
 # * recursive
 #
@@ -4947,6 +5097,49 @@ function bl64_fs_fix_permissions() {
   local path=''
 
   # Remove consumed parameters
+  shift
+  shift
+
+  bl64_fs_path_permission_set \
+    "$file_mode" \
+    "$dir_mode" \
+    "$BL64_VAR_DEFAULT" \
+    "$BL64_VAR_DEFAULT" \
+    "$@"
+}
+
+#######################################
+# Set path permissions and ownership
+#
+# * Path: directory and/or file only
+# * Allow different permissions for files and directories
+# * Requires root privilege if current user is not the path owner
+# * Path wildcards are not allowed
+# * Recursive
+#
+# Arguments:
+#   $1: file permissions. Format: chown format. Default: no change
+#   $2: directory permissions. Format: chown format. Default: no change
+#   $3: user name. Default: no change
+#   $4: group name. Default: no change
+#   $@: list of paths. Must use full path for each
+# Outputs:
+#   STDOUT: command stdin
+#   STDERR: command stderr
+# Returns:
+#   0: operation completed ok
+#   >0: operation failed
+#######################################
+function bl64_fs_path_permission_set() {
+  bl64_dbg_lib_show_function "$@"
+  local file_mode="${1:-${BL64_VAR_DEFAULT}}"
+  local dir_mode="${2:-${BL64_VAR_DEFAULT}}"
+  local user="${3:-${BL64_VAR_DEFAULT}}"
+  local group="${4:-${BL64_VAR_DEFAULT}}"
+
+  # Remove consumed parameters
+  shift
+  shift
   shift
   shift
 
@@ -4972,6 +5165,26 @@ function bl64_fs_fix_permissions() {
       ${BL64_FS_SET_FIND_STAY} \
       ${BL64_FS_SET_FIND_TYPE_DIR} \
       ${BL64_FS_SET_FIND_RUN} "$BL64_FS_CMD_CHMOD" "$dir_mode" "{}" \; ||
+      return $?
+  fi
+
+  if [[ "$user" != "$BL64_VAR_DEFAULT" ]]; then
+    bl64_msg_show_lib_subtask "${_BL64_FS_TXT_SET_OWNER} (${user} ${BL64_MSG_COSMETIC_ARROW2} ${*})"
+    # shellcheck disable=SC2086
+    bl64_fs_run_chown \
+      $BL64_FS_SET_CHOWN_RECURSIVE \
+      "${user}" \
+      "$@" ||
+      return $?
+  fi
+
+  if [[ "$group" != "$BL64_VAR_DEFAULT" ]]; then
+    bl64_msg_show_lib_subtask "${_BL64_FS_TXT_SET_GROUP} (${group} ${BL64_MSG_COSMETIC_ARROW2} ${*})"
+    # shellcheck disable=SC2086
+    bl64_fs_run_chown \
+      $BL64_FS_SET_CHOWN_RECURSIVE \
+      ":${group}" \
+      "$@" ||
       return $?
   fi
 
@@ -5323,8 +5536,8 @@ function bl64_fs_check_new_dir() {
 #   $2: destination path
 #   $3: overwrite if already present?
 # Outputs:
-#   STDOUT: command dependant
-#   STDERR: command dependant
+#   STDOUT: verbose operation
+#   STDOUT: command errors
 # Returns:
 #   0: operation completed ok
 #   >0: operation failed
@@ -5484,7 +5697,7 @@ TERM="${TERM:-vt100}"
 
 # shellcheck disable=SC2034
 {
-  declare BL64_VERSION='19.5.4'
+  declare BL64_VERSION='20.1.1'
 
   #
   # Imported shell standard variables
@@ -5646,6 +5859,8 @@ function bl64_lib_mode_strict_is_enabled { bl64_lib_flag_is_enabled "$BL64_LIB_S
 
 function bl64_lib_lang_is_enabled { bl64_lib_flag_is_enabled "$BL64_LIB_LANG"; }
 function bl64_lib_trap_is_enabled { bl64_lib_flag_is_enabled "$BL64_LIB_TRAPS"; }
+
+function bl64_lib_var_is_default { local value="${1:-}"; [[ "$value" == "$BL64_VAR_DEFAULT" ]]; }
 
 #######################################
 # Determines if the flag variable is enabled or not
@@ -5997,7 +6212,7 @@ function bl64_lib_module_imported() {
 
 # shellcheck disable=SC2034
 {
-  declare BL64_MSG_VERSION='5.0.1'
+  declare BL64_MSG_VERSION='5.1.0'
 
   declare BL64_MSG_MODULE='0'
 
@@ -6026,6 +6241,7 @@ function bl64_lib_module_imported() {
   declare BL64_MSG_TYPE_BATCHOK='BATCHOK'
   declare BL64_MSG_TYPE_ERROR='ERROR'
   declare BL64_MSG_TYPE_INFO='INFO'
+  declare BL64_MSG_TYPE_INIT='INIT'
   declare BL64_MSG_TYPE_INPUT='INPUT'
   declare BL64_MSG_TYPE_LIBINFO='LIBINFO'
   declare BL64_MSG_TYPE_LIBSUBTASK='LIBSUBTASK'
@@ -6073,6 +6289,7 @@ function bl64_lib_module_imported() {
   declare BL64_MSG_THEME_ASCII_STD_FMTHOST=''
   declare BL64_MSG_THEME_ASCII_STD_FMTTIME=''
   declare BL64_MSG_THEME_ASCII_STD_INFO='(I)'
+  declare BL64_MSG_THEME_ASCII_STD_INIT='(:)'
   declare BL64_MSG_THEME_ASCII_STD_INPUT='(?)'
   declare BL64_MSG_THEME_ASCII_STD_LIBINFO='(II)'
   declare BL64_MSG_THEME_ASCII_STD_LIBSUBTASK='(>>)'
@@ -6093,6 +6310,7 @@ function bl64_lib_module_imported() {
   declare BL64_MSG_THEME_ANSI_STD_FMTHOST='34'
   declare BL64_MSG_THEME_ANSI_STD_FMTTIME='36'
   declare BL64_MSG_THEME_ANSI_STD_INFO='36'
+  declare BL64_MSG_THEME_ANSI_STD_INIT='36'
   declare BL64_MSG_THEME_ANSI_STD_INPUT='5;30;47'
   declare BL64_MSG_THEME_ANSI_STD_LIBINFO='1;32'
   declare BL64_MSG_THEME_ANSI_STD_LIBSUBTASK='1;36'
@@ -6177,6 +6395,7 @@ function bl64_lib_module_imported() {
   declare _BL64_MSG_TXT_COMMANDS='Commands'
   declare _BL64_MSG_TXT_ERROR='Error'
   declare _BL64_MSG_TXT_FLAGS='Flags'
+  declare _BL64_MSG_TXT_INIT='Init'
   declare _BL64_MSG_TXT_INFO='Info'
   declare _BL64_MSG_TXT_INPUT='Input'
   declare _BL64_MSG_TXT_INVALID_VALUE='invalid value. Not one of'
@@ -8372,6 +8591,28 @@ function bl64_msg_show_warning() {
 
   bl64_log_warning "${FUNCNAME[1]:-MAIN}" "$message" &&
     _bl64_msg_print "$BL64_MSG_TYPE_WARNING" "$_BL64_MSG_TXT_WARNING" "$message" >&2
+}
+
+#######################################
+# Display script initialization message
+#
+# Arguments:
+#   $1: message
+# Outputs:
+#   STDOUT: message
+#   STDERR: None
+# Returns:
+#   0: successfull execution
+#   >0: printf error
+#######################################
+function bl64_msg_show_init() {
+  bl64_dbg_lib_msg_enabled && bl64_dbg_lib_show_function "$@"
+  local message="$1"
+
+  bl64_log_info "${FUNCNAME[1]:-MAIN}" "$message" &&
+    bl64_msg_app_verbose_enabled || return 0
+
+  _bl64_msg_print "$BL64_MSG_TYPE_INIT" "$_BL64_MSG_TXT_INIT" "$message"
 }
 
 #######################################
