refact: upgrade bashlib64

diff --git a/cntbuild b/cntbuild
--- a/cntbuild
+++ b/cntbuild
@@ -5,7 +5,7 @@
 # Author: serdigital64 (https://github.com/serdigital64)
 # License: GPL-3.0-or-later (https://www.gnu.org/licenses/gpl-3.0.txt)
 # Repository: https://github.com/automation64/container64
-# Version: 1.2.0
+# Version: 1.3.0
 #######################################
 
 #
@@ -99,7 +99,7 @@ TERM="${TERM:-vt100}"
 # BashLib64 / Module / Globals / Setup script run-time environment
 #######################################
 
-export BL64_VERSION='12.5.0'
+export BL64_VERSION='12.6.0'
 
 # Declare imported variables
 export LANG
@@ -230,7 +230,7 @@ export _BL64_BSH_TXT_UNSUPPORTED='BashLib64 is not supported in the current Bash
 # BashLib64 / Module / Globals / Check for conditions and report status
 #######################################
 
-export BL64_CHECK_VERSION='3.2.0'
+export BL64_CHECK_VERSION='3.3.0'
 
 export BL64_CHECK_MODULE="$BL64_VAR_OFF"
 
@@ -241,6 +241,7 @@ export _BL64_CHECK_TXT_PARAMETER_DEFAULT='required parameter value must be other
 export _BL64_CHECK_TXT_COMMAND_NOT_FOUND='required command is not present'
 export _BL64_CHECK_TXT_COMMAND_NOT_EXECUTABLE='required command is present but has no execution permission'
 export _BL64_CHECK_TXT_COMMAND_NOT_INSTALLED='required command is not installed'
+export _BL64_CHECK_TXT_COMMAND_NOT_IN_PATH='required command is not found in any of the search paths'
 
 export _BL64_CHECK_TXT_FILE_NOT_FOUND='required file is not present'
 export _BL64_CHECK_TXT_FILE_NOT_FILE='path is present but is not a regular file'
@@ -360,12 +361,14 @@ export _BL64_DBG_TXT_DEBUG='Debug'
 # BashLib64 / Module / Globals / Manage local filesystem
 #######################################
 
-export BL64_FS_VERSION='4.2.2'
+export BL64_FS_VERSION='4.3.0'
 
 export BL64_FS_MODULE="$BL64_VAR_OFF"
 
 export BL64_FS_PATH_TEMPORAL=''
 export BL64_FS_PATH_CACHE=''
+# Location for temporary files generated by bashlib64 functions
+export BL64_FS_PATH_TMP='/tmp'
 
 export BL64_FS_CMD_CHMOD=''
 export BL64_FS_CMD_CHOWN=''
@@ -405,12 +408,14 @@ export BL64_FS_SET_LN_VERBOSE=''
 export BL64_FS_SET_LS_NOCOLOR=''
 export BL64_FS_SET_MKDIR_PARENTS=''
 export BL64_FS_SET_MKDIR_VERBOSE=''
+export BL64_FS_SET_MKTEMP_DIRECTORY=''
+export BL64_FS_SET_MKTEMP_QUIET=''
+export BL64_FS_SET_MKTEMP_TMPDIR=''
 export BL64_FS_SET_MV_FORCE=''
 export BL64_FS_SET_MV_VERBOSE=''
 export BL64_FS_SET_RM_FORCE=''
 export BL64_FS_SET_RM_RECURSIVE=''
 export BL64_FS_SET_RM_VERBOSE=''
-
 
 export BL64_FS_UMASK_RW_USER='u=rwx,g=,o='
 export BL64_FS_UMASK_RW_GROUP='u=rwx,g=rwx,o='
@@ -420,16 +425,21 @@ export BL64_FS_UMASK_RW_GROUP_RO_ALL='u=rwx,g=rwx,o=rx'
 
 export BL64_FS_SAFEGUARD_POSTFIX='.bl64_fs_safeguard'
 
-export _BL64_FS_TXT_COPY_FILE_PATH='copy file'
-export _BL64_FS_TXT_CREATE_DIR_PATH='create directory'
-export _BL64_FS_TXT_MERGE_ADD_SOURCE='merge content from source'
-export _BL64_FS_TXT_RESTORE_OBJECT='restore original file from backup'
-export _BL64_FS_TXT_SAFEGUARD_FAILED='unable to safeguard requested path'
-export _BL64_FS_TXT_SAFEGUARD_OBJECT='backup original file'
+export BL64_FS_TMP_PREFIX='bl64tmp'
+
 export _BL64_FS_TXT_CLEANUP_CACHES='clean up OS cache contents'
 export _BL64_FS_TXT_CLEANUP_LOGS='clean up OS logs'
 export _BL64_FS_TXT_CLEANUP_TEMP='clean up OS temporary files'
+export _BL64_FS_TXT_COPY_FILE_PATH='copy file'
+export _BL64_FS_TXT_CREATE_DIR_PATH='create directory'
+export _BL64_FS_TXT_MERGE_ADD_SOURCE='merge content from source'
 export _BL64_FS_TXT_MERGE_DIRS='merge directories content'
+export _BL64_FS_TXT_RESTORE_OBJECT='restore original file from backup'
+export _BL64_FS_TXT_SAFEGUARD_FAILED='unable to safeguard requested path'
+export _BL64_FS_TXT_SAFEGUARD_OBJECT='backup original file'
+
+export _BL64_FS_TXT_ERROR_NOT_TMPDIR='provided directory was not created by bl64_fs_create_tmpdir'
+export _BL64_FS_TXT_ERROR_NOT_TMPFILE='provided directory was not created by bl64_fs_create_tmpfile'
 
 #######################################
 # BashLib64 / Module / Globals / Format text data
@@ -2136,6 +2146,42 @@ function bl64_check_home() {
 }
 
 #######################################
+# Check and report if the command is available using the current search path
+#
+# * standar PATH variable is used for the search
+# * aliases and built-in commands will always return true
+# * if the command is in the search path, then bl64_check_command is used to ensure it can be used
+#
+# Arguments:
+#   $1: command file name
+#   $2: Not found error message. Default: _BL64_CHECK_TXT_COMMAND_NOT_IN_PATH
+# Outputs:
+#   STDOUT: None
+#   STDERR: Error message
+# Returns:
+#   0: Command found
+#   BL64_LIB_ERROR_FILE_NOT_FOUND
+#######################################
+function bl64_check_command_search_path() {
+  bl64_dbg_lib_show_function "$@"
+  local file="${1:-}"
+  local message="${2:-${_BL64_CHECK_TXT_COMMAND_NOT_IN_PATH}}"
+  local full_path=''
+
+  bl64_check_parameter 'file' || return $?
+
+  full_path="$(type -p "${file}")"
+  # shellcheck disable=SC2181
+  if (( $? != 0)); then
+    bl64_msg_show_error "${message} (command: ${file} ${BL64_MSG_COSMETIC_PIPE} ${_BL64_CHECK_TXT_FUNCTION}: ${FUNCNAME[1]:-NONE}@${BASH_LINENO[1]:-NONE})"
+    # shellcheck disable=SC2086
+    return $BL64_LIB_ERROR_FILE_NOT_FOUND
+  fi
+
+  bl64_check_command "$full_path"
+}
+
+#######################################
 # BashLib64 / Module / Setup / Show shell debugging inlevelion
 #######################################
 
@@ -2703,6 +2749,7 @@ function _bl64_fs_set_command() {
 # Create command sets for common options
 #
 # * Warning: bootstrap function
+# * BL64_FS_SET_MKTEMP_TMPDIR: not using long form (--) as it requires =
 #
 # Arguments:
 #   None
@@ -2733,6 +2780,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='--parents'
     BL64_FS_SET_MKDIR_VERBOSE='--verbose'
+    BL64_FS_SET_MKTEMP_DIRECTORY='--directory'
+    BL64_FS_SET_MKTEMP_QUIET='--quiet'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='--force'
     BL64_FS_SET_MV_VERBOSE='--verbose'
     BL64_FS_SET_RM_FORCE='--force'
@@ -2757,6 +2807,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='--parents'
     BL64_FS_SET_MKDIR_VERBOSE='--verbose'
+    BL64_FS_SET_MKTEMP_DIRECTORY='--directory'
+    BL64_FS_SET_MKTEMP_QUIET='--quiet'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='--force'
     BL64_FS_SET_MV_VERBOSE='--verbose'
     BL64_FS_SET_RM_FORCE='--force'
@@ -2781,6 +2834,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='--parents'
     BL64_FS_SET_MKDIR_VERBOSE='--verbose'
+    BL64_FS_SET_MKTEMP_DIRECTORY='--directory'
+    BL64_FS_SET_MKTEMP_QUIET='--quiet'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='--force'
     BL64_FS_SET_MV_VERBOSE='--verbose'
     BL64_FS_SET_RM_FORCE='--force'
@@ -2805,6 +2861,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='-p'
     BL64_FS_SET_MKDIR_VERBOSE=' '
+    BL64_FS_SET_MKTEMP_DIRECTORY='-d'
+    BL64_FS_SET_MKTEMP_QUIET='-q'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='-f'
     BL64_FS_SET_MV_VERBOSE=' '
     BL64_FS_SET_RM_FORCE='-f'
@@ -2829,6 +2888,9 @@ function _bl64_fs_set_options() {
     BL64_FS_SET_LS_NOCOLOR='--color=never'
     BL64_FS_SET_MKDIR_PARENTS='-p'
     BL64_FS_SET_MKDIR_VERBOSE='-v'
+    BL64_FS_SET_MKTEMP_DIRECTORY='-d'
+    BL64_FS_SET_MKTEMP_QUIET='-q'
+    BL64_FS_SET_MKTEMP_TMPDIR='-p'
     BL64_FS_SET_MV_FORCE='-f'
     BL64_FS_SET_MV_VERBOSE='-v'
     BL64_FS_SET_RM_FORCE='-f'
@@ -3128,6 +3190,31 @@ function bl64_fs_run_chown() {
   bl64_dbg_lib_trace_start
   # shellcheck disable=SC2086
   "$BL64_FS_CMD_CHOWN" $verbose "$@"
+  bl64_dbg_lib_trace_stop
+}
+
+#######################################
+# Command wrapper with verbose, debug and common options
+#
+# * Warning: mktemp with no arguments creates a temp file by default
+#
+# Arguments:
+#   $@: arguments are passed as-is to the command
+# Outputs:
+#   STDOUT: command output
+#   STDERR: command stderr
+# Returns:
+#   command exit status
+#######################################
+function bl64_fs_run_mktemp() {
+  bl64_dbg_lib_show_function "$@"
+  local verbose="$BL64_FS_SET_MKTEMP_QUIET"
+
+  bl64_dbg_lib_command_enabled && verbose=''
+
+  bl64_dbg_lib_trace_start
+  # shellcheck disable=SC2086
+  "$BL64_FS_CMD_MKTEMP" $verbose "$@"
   bl64_dbg_lib_trace_stop
 }
 
@@ -3860,6 +3947,109 @@ function bl64_fs_set_ephemeral() {
   fi
 
   return 0
+}
+
+#######################################
+# Create temporal directory
+#
+# * Wrapper to the mktemp tool
+#
+# Arguments:
+#   None
+# Outputs:
+#   STDOUT: full path to temp dir
+#   STDERR: error messages
+# Returns:
+#   0: temp created ok
+#  >0: failed to create temp
+#######################################
+function bl64_fs_create_tmpdir() {
+  bl64_dbg_lib_show_function
+  local template="${BL64_FS_TMP_PREFIX}-${BL64_SCRIPT_NAME}.XXXXXXXXXX"
+
+  bl64_fs_run_mktemp \
+    "$BL64_FS_SET_MKTEMP_DIRECTORY" \
+    "$BL64_FS_SET_MKTEMP_TMPDIR" "$BL64_FS_PATH_TMP" \
+    "$template"
+}
+
+#######################################
+# Create temporal file
+#
+# * Wrapper to the mktemp tool
+#
+# Arguments:
+#   None
+# Outputs:
+#   STDOUT: full path to temp file
+#   STDERR: error messages
+# Returns:
+#   0: temp created ok
+#  >0: failed to create temp
+#######################################
+function bl64_fs_create_tmpfile() {
+  bl64_dbg_lib_show_function
+  local template="${BL64_FS_TMP_PREFIX}-${BL64_SCRIPT_NAME}.XXXXXXXXXX"
+
+  bl64_fs_run_mktemp \
+    "$BL64_FS_SET_MKTEMP_TMPDIR" "$BL64_FS_PATH_TMP" \
+    "$template"
+}
+
+#######################################
+# Remove temporal directory created by bl64_fs_create_tmpdir
+#
+# Arguments:
+#   $1: full path to the tmpdir
+# Outputs:
+#   STDOUT: None
+#   STDERR: error messages
+# Returns:
+#   0: temp removed ok
+#  >0: failed to remove temp
+#######################################
+function bl64_fs_rm_tmpdir() {
+  bl64_dbg_lib_show_function "$@"
+  local tmpdir="$1"
+
+  bl64_check_parameter 'tmpdir' &&
+    bl64_check_directory "$tmpdir" ||
+    return $?
+
+  if [[ "$tmpdir" != ${BL64_FS_PATH_TMP}/${BL64_FS_TMP_PREFIX}-*.* ]]; then
+    bl64_msg_show_error "${_BL64_FS_TXT_ERROR_NOT_TMPDIR} (${tmpdir})"
+    return $BL64_LIB_ERROR_TASK_FAILED
+  fi
+
+  bl64_fs_rm_full "$tmpdir"
+}
+
+#######################################
+# Remove temporal file create by bl64_fs_create_tmpfile
+#
+# Arguments:
+#   $1: full path to the tmpfile
+# Outputs:
+#   STDOUT: None
+#   STDERR: error messages
+# Returns:
+#   0: temp removed ok
+#  >0: failed to remove temp
+#######################################
+function bl64_fs_rm_tmpfile() {
+  bl64_dbg_lib_show_function "$@"
+  local tmpfile="$1"
+
+  bl64_check_parameter 'tmpfile' &&
+    bl64_check_file "$tmpfile" ||
+    return $?
+
+  if [[ "$tmpfile" != ${BL64_FS_PATH_TMP}/${BL64_FS_TMP_PREFIX}-*.* ]]; then
+    bl64_msg_show_error "${_BL64_FS_TXT_ERROR_NOT_TMPFILE} (${tmpfile})"
+    return $BL64_LIB_ERROR_TASK_FAILED
+  fi
+
+  bl64_fs_rm_file "$tmpfile"
 }
 
 #######################################
@@ -7142,8 +7332,9 @@ function bl64_vcs_github_run_api() {
   bl64_check_parameter 'api_call' ||
     return $?
 
+  # shellcheck disable=SC2086
   bl64_rxtx_run_curl \
-    "$BL64_RXTX_SET_CURL_SILENT" \
+    $BL64_RXTX_SET_CURL_SILENT \
     "${BL64_VCS_GITHUB_API_URL}/${api_call}"
 }
 
@@ -13718,7 +13909,7 @@ export CNTBUILD_DOCKERFILE_NAME='Dockerfile'
 #
 
 function cntbuild_list() {
-  bl64_dbg_app_show_function
+  bl64_dbg_app_show_function "$@"
   local context="$1"
 
   bl64_check_parameter 'context' &&
@@ -13731,7 +13922,7 @@ function cntbuild_list() {
 }
 
 function cntbuild_build() {
-  bl64_dbg_app_show_function
+  bl64_dbg_app_show_function "$@"
   local container="$1"
   local tag="$2"
   local context="$3"
@@ -13745,14 +13936,13 @@ function cntbuild_build() {
     bl64_check_parameter 'context' ||
     return $?
 
-  # Determine if standard labels are provided
   if [[ -f "$labels_file" ]]; then
-    # Load each label and add to the command line
+    bl64_dbg_app_show_info "get container labels (${labels_file})"
     IFS=$'\n'
     for labels_record in $(<"${labels_file}"); do
       unset IFS
       # shellcheck disable=SC2004
-      command_line[${labels_index}]="--label='$labels_record'"
+      command_line[${labels_index}]="--label=$labels_record"
       labels_index=$((labels_index + 1))
 
       # Extract the container version if provided
@@ -13763,13 +13953,18 @@ function cntbuild_build() {
       fi
 
     done
+    bl64_dbg_app_show_info "labels: ${command_line[*]}"
   fi
 
-  bl64_cnt_build "$context" "${CNTBUILD_DOCKERFILE_SOURCES}/${container}/${CNTBUILD_DOCKERFILE_NAME}" "${container}:${tag}" "${command_line[@]}"
+  bl64_cnt_build \
+    "$context" \
+    "${CNTBUILD_DOCKERFILE_SOURCES}/${container}/${CNTBUILD_DOCKERFILE_NAME}" \
+    "${container}:${tag}" \
+    "${command_line[@]}"
 }
 
 function cntbuild_open() {
-  bl64_dbg_app_show_function
+  bl64_dbg_app_show_function "$@"
   local container="$1"
   local tag="$2"
   local context="$3"
@@ -13788,7 +13983,7 @@ function cntbuild_open() {
 }
 
 function cntbuild_publish() {
-  bl64_dbg_app_show_function
+  bl64_dbg_app_show_function "$@"
   local container="$1"
   local tag="$2"
   local context="$3"
@@ -13811,16 +14006,8 @@ function cntbuild_publish() {
 
 }
 
-function cntbuild_setup_globals() {
-  :
-}
-
-function cntbuild_check_requirements() {
-  [[ -z "$cntbuild_command" ]] && cntbuild_help && return 1
-  return 0
-}
-
 function cntbuild_get_version() {
+  bl64_dbg_app_show_function "@"
   local container="$1"
   local context="$2"
   local labels_file="${context}/${CNTBUILD_DOCKERFILE_SOURCES}/${container}/${CNTBUILD_METADATA_FILE}"
@@ -13841,13 +14028,45 @@ function cntbuild_get_version() {
       fi
     done
   fi
-
 }
 
+#######################################
+# Initialize environment
+#
+# Arguments:
+#   None
+# Outputs:
+#   Initializacion progress messages
+# Returns:
+#   0: initialization ok
+#   >: failed to initialize
+#######################################
+function cntbuild_initialize() {
+  bl64_dbg_app_show_function "@"
+  local command="$1"
+
+  bl64_check_parameter 'command' ||
+    { cntbuild_help && return 1; }
+
+  bl64_cnt_setup || return $?
+
+  return 0
+}
+
+#######################################
+# Show script usage description
+#
+# Arguments:
+#   None
+# Outputs:
+#   Command line format and description
+# Returns:
+#   0
+#######################################
 function cntbuild_help() {
 
   bl64_msg_show_usage \
-    '<-b|-u|-l|-n> [-c Container] [-e Tag] [-o Context] [-h]' \
+    '<-b|-u|-l|-n> [-c Container] [-e Tag] [-o Context] [-V Verbose] [-D Debug] [-h]' \
     'Build containers in dev environment' \
     '
   -b          : Build container
@@ -13860,6 +14079,8 @@ function cntbuild_help() {
   -c Container: Container name: Format: base directory where the Dockerfile is. Required for -b, -l, -n
   -e Tag      : Container tag. Format: tag. Default: 0.1.0
   -o Context  : Build context. Format: full path. Default: PWD/src
+  -V Verbose  : Set verbosity level. Format: one of BL64_MSG_VERBOSE_*
+  -D Debug    : Enable debugging mode. Format: one of BL64_DBG_TARGET_*
   "
 
 }
@@ -13868,45 +14089,35 @@ function cntbuild_help() {
 #
 
 declare cntbuild_status=1
-declare cntbuild_command_tag=''
-declare cntbuild_command=''
+declare cntbuild_debug="$BL64_DBG_TARGET_NONE"
+declare cntbuild_verbose="$BL64_MSG_VERBOSE_APP"
 declare cntbuild_option=''
+declare cntbuild_command="$BL64_VAR_NULL"
 declare cntbuild_container=''
 declare cntbuild_tag='0.1.0'
 declare cntbuild_context=''
 cntbuild_context="$(pwd)/src"
 
 (($# == 0)) && cntbuild_help && exit 1
-while getopts ':bulnc:e:o:h' cntbuild_option; do
+while getopts ':bulnc:e:o:V:D:h' cntbuild_option; do
   case "$cntbuild_option" in
-  b)
-    cntbuild_command='cntbuild_build'
-    cntbuild_command_tag='build container'
-    ;;
-  u)
-    cntbuild_command='cntbuild_publish'
-    cntbuild_command_tag='publish images to external registry'
-    ;;
-  l)
-    cntbuild_command='cntbuild_list'
-    cntbuild_command_tag='list container sources'
-    ;;
-  n)
-    cntbuild_command='cntbuild_open'
-    cntbuild_command_tag='open local container image'
-    ;;
+  b) cntbuild_command='cntbuild_build' ;;
+  u) cntbuild_command='cntbuild_publish' ;;
+  l) cntbuild_command='cntbuild_list' ;;
+  n) cntbuild_command='cntbuild_open' ;;
   c) cntbuild_container="$OPTARG" ;;
   e) cntbuild_tag="$OPTARG" ;;
   o) cntbuild_context="$OPTARG" ;;
+  V) cntbuild_verbose="$OPTARG" ;;
+  D) cntbuild_debug="$OPTARG" ;;
   h) cntbuild_help && exit 0 ;;
   *) cntbuild_help && exit 1 ;;
   esac
 done
-cntbuild_setup_globals &&
-  cntbuild_check_requirements &&
-  bl64_cnt_setup || exit
+bl64_dbg_set_level "$cntbuild_debug" && bl64_msg_set_level "$cntbuild_verbose" || exit $?
+cntbuild_initialize "$cntbuild_command" || exit $?
 
-bl64_msg_show_batch_start "$cntbuild_command_tag"
+bl64_msg_show_batch_start "$cntbuild_command"
 case "$cntbuild_command" in
 'cntbuild_build' | 'cntbuild_publish' | 'cntbuild_open') "$cntbuild_command" "$cntbuild_container" "$cntbuild_tag" "$cntbuild_context" ;;
 'cntbuild_list') "$cntbuild_command" "$cntbuild_context" ;;
@@ -13914,5 +14125,5 @@ case "$cntbuild_command" in
 esac
 cntbuild_status=$?
 
-bl64_msg_show_batch_finish $cntbuild_status "$cntbuild_command_tag"
+bl64_msg_show_batch_finish $cntbuild_status "$cntbuild_command"
 exit $cntbuild_status
