feat: add mirror (#135)

diff --git a/src/helpers/pen-test/setup b/src/helpers/pen-test/setup
--- a/src/helpers/pen-test/setup
+++ b/src/helpers/pen-test/setup
@@ -33,20 +33,46 @@ export CNT64_DEBUG="${CNT64_DEBUG:-}"
 export CNT64_USER="${CNT64_USER:-}"
 
 # source-path=lib/bl64
-# X_IMPORTS_PLACEHOLDER_X
-source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
 #
 
-# X_GLOBALS_PLACEHOLDER_X
-
 #
 # Functions
 #
 
-# X_FUNCIONS_PLACEHOLDER_X
+function cnt64_setup_select_packages() {
+  bl64_dbg_app_show_function
+  local packages=''
+  if bl64_os_match "${BL64_OS_KL}"; then
+    packages="${packages} kali-linux-headless"
+  fi
+  [[ -z "$packages" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  echo "$packages"
+}
+
+function cnt64_setup_install_packages() {
+  bl64_dbg_app_show_function
+  local packages=''
+  bl64_msg_show_task 'deploy packages'
+  packages="$(cnt64_setup_select_packages)" ||
+    return $?
+  # shellcheck disable=SC2086
+  bl64_pkg_deploy $packages
+}
 
 #######################################
 # Initialize environment
@@ -61,11 +87,10 @@ source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load
 #######################################
 function cnt64_setup_initialize() {
   bl64_dbg_app_show_function
-  # X_SETUP_PLACEHOLDER_X
   bl64_os_check_version \
-    "X_TARGET_OS1_X" \
-    "X_TARGET_OSN_X" &&
-    bl64_check_privilege_root
+    "${BL64_OS_KL}" \
+    bl64_check_privilege_root &&
+    bl64_pkg_setup
 }
 
 #
@@ -79,6 +104,6 @@ bl64_msg_show_batch_start "$cnt64_setup_installer_description"
 
 [[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
 cnt64_setup_initialize &&
-# X_MAIN_PLACEHOLDER_X
+  cnt64_setup_install_packages
 
 bl64_msg_show_batch_finish $? "$cnt64_setup_installer_description"
