refact: upgrade base env

diff --git a/src/installer/install-helm b/src/installer/install-helm
--- a/src/installer/install-helm
+++ b/src/installer/install-helm
@@ -1,64 +1,139 @@
 #!/usr/bin/env bash
+# Template: 1.0.0
+#######################################
+# Container64 / Package installer
+#
+# Author: SerDigital64 (https://github.com/serdigital64)
+# Repository: https://github.com/automation64/container64
+# Version: 1.0.0
+#
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
 
-# shellcheck disable=SC1091
-source "/toolbox.env" || exit $?
-# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash disable=SC2154
-source "$CNT64_BASHLIB64" || exit $?
+#
+# Imports
+#
+
+# Environment Definition. See docs/base-environment.md for details
+export CNT64_BASHLIB64
+export CNT64_DEBUG="${CNT64_DEBUG:-}"
+export CNT64_LOCAL_BIN
+export CNT64_OPT_ROOT
+
+# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
+source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+
+#
+# Globals
+#
+
+export CNT64_HELM_PLATFORM="${CNT64_HELM_PLATFORM:-linux-amd64}"
+export CNT64_HELM_SOURCE="${CNT64_HELM_SOURCE:-https://get.helm.sh}"
+export CNT64_HELM_TARGET="${CNT64_HELM_TARGET:-${CNT64_OPT_ROOT}/helm}"
+export CNT64_HELM_VERSION="${CNT64_HELM_VERSION:-latest}"
 
 #
 # Functions
 #
 
-function cnt64_hlm3_provision() {
-  local package_installer='linux-amd64'
-  local package_installer_bin="${package_installer}/helm"
-  local package_source='helm-v3.11.0-linux-amd64.tar.gz'
-  local package_url='https://get.helm.sh'
-  local app_mode='0755'
-  local app_root='/usr/local'
-  local app_bin="${app_root}/bin"
-  local app_cli="${app_bin}/helm"
+#######################################
+# Install application packages
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package installer progress and errors
+# Returns:
+#   0: package installed ok
+#   >0: unable to install package
+#######################################
+function cnt64_helm_install() {
+  bl64_dbg_app_show_function
+  local repo_owner='helm'
+  local repo_name='helm'
+  local package_prefix='helm'
+  local package_sufix='.tar.gz'
+  local package_name=''
+  local package_url="$CNT64_HELM_SOURCE"
+  local work_path=''
+  local app_target_mode='0755'
+  local app_target_owner='root'
+  local app_cli_mode='0755'
+  local app_cli='helm'
 
   bl64_msg_show_task 'download application'
-  # shellcheck disable=SC2154
-  package_installer="${CNT64_TMP}/${package_installer}"
-  package_installer_bin="${CNT64_TMP}/${package_installer_bin}"
-  bl64_rxtx_web_get_file "${package_url}/${package_source}" "${CNT64_TMP}/${package_source}" &&
-    bl64_arc_open_tar "${CNT64_TMP}/${package_source}" "${CNT64_TMP}" &&
-    bl64_check_command "$package_installer_bin" ||
+  work_path="$(bl64_fs_create_tmpdir)" || return $?
+  if [[ "$CNT64_HELM_VERSION" == 'latest' ]]; then
+    CNT64_HELM_VERSION="$(bl64_vcs_github_release_get_latest "$repo_owner" "$repo_name")" ||
+      return $?
+  fi
+  package_name="${package_prefix}-${CNT64_HELM_VERSION}-${CNT64_HELM_PLATFORM}${package_sufix}"
+
+  bl64_rxtx_web_get_file "${package_url}/${package_name}" "${work_path}/${package_name}" &&
+    bl64_arc_open_tar "${work_path}/${package_name}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
-  bl64_fs_create_dir "$app_mode" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$app_root" "$app_bin" &&
-    bl64_fs_copy_files "$app_mode" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$app_bin" "$package_installer_bin" &&
-    bl64_check_command "$app_cli" &&
-    bl64_msg_show_info "Application file: ${app_cli}" ||
+  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$CNT64_HELM_TARGET" &&
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$CNT64_HELM_TARGET" "${work_path}/${CNT64_HELM_PLATFORM}/${app_cli}" ||
     return $?
 
-  bl64_msg_show_task "clean temporary files"
-  bl64_fs_rm_full "$package_installer"
+  bl64_msg_show_task "publish application to searchable path (${CNT64_LOCAL_BIN})"
+  # shellcheck disable=SC2086
+  bl64_fs_run_ln $BL64_FS_SET_LN_SYMBOLIC "${CNT64_HELM_TARGET}/${app_cli}" "${CNT64_LOCAL_BIN}/${app_cli}" ||
+    return $?
 
+  bl64_msg_show_task 'cleanup temporary files'
+  bl64_fs_rm_tmpdir "$work_path"
   return 0
+}
+
+#######################################
+# Initialize environment
+#
+# Arguments:
+#   None
+# Outputs:
+#   Initializacion progress messages
+# Returns:
+#   0: initialization ok
+#   >: failed to initialize
+#######################################
+function cnt64_helm_initialize() {
+  bl64_dbg_app_show_function
+  bl64_check_export 'CNT64_LOCAL_BIN' &&
+    bl64_check_export 'CNT64_OPT_ROOT' &&
+    bl64_arc_setup &&
+    bl64_check_privilege_root
 }
 
 #
 # Main
 #
 
-declare cnt64_hlm3_process='Install Helm 3'
-declare -i cnt64_hlm3_status=0
-
-[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
-bl64_arc_setup &&
-  bl64_check_privilege_root ||
-  exit $?
+declare cnt64_helm_installer_description='Install package: Helm'
+declare -i cnt64_helm_status=0
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start "$cnt64_hlm3_process"
+bl64_msg_show_batch_start "$cnt64_helm_installer_description"
 
-cnt64_hlm3_provision
-cnt64_hlm3_status=$?
+[[ -n "$CNT64_DEBUG" ]] && bl64_dbg_lib_enable
+cnt64_helm_initialize &&
+  cnt64_helm_install
+cnt64_helm_status=$?
 
-bl64_fs_cleanup_full
-bl64_msg_show_batch_finish "$cnt64_hlm3_status" "$cnt64_hlm3_process"
-exit $cnt64_hlm3_status
+bl64_msg_show_batch_finish "$cnt64_helm_status" "$cnt64_helm_installer_description"
+exit $cnt64_helm_status
