refact: upgrade base env

diff --git a/src/installer/install-bashlib64 b/src/installer/install-bashlib64
--- a/src/installer/install-bashlib64
+++ b/src/installer/install-bashlib64
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 # Template: 1.0.0
 #######################################
 # Container64 / Package installer
@@ -34,8 +34,8 @@ export CNT64_DEBUG="${CNT64_DEBUG:-}"
 # Globals
 #
 
-CNT64_BASHLIB64_TARGET="${CNT64_BASHLIB64_TARGET:-/opt/bl64}"
-CNT64_BASHLIB64_SOURCE="${CNT64_BASHLIB64_SOURCE:-https://raw.githubusercontent.com/automation64/bashlib64/main/bashlib64.bash}"
+export CNT64_BASHLIB64_TARGET="${CNT64_BASHLIB64_TARGET:-/opt/bl64}"
+export CNT64_BASHLIB64_SOURCE="${CNT64_BASHLIB64_SOURCE:-https://raw.githubusercontent.com/automation64/bashlib64/main/bashlib64.bash}"
 
 #
 # Functions
@@ -52,11 +52,11 @@ CNT64_BASHLIB64_SOURCE="${CNT64_BASHLIB64_SOURCE:-https://raw.githubusercontent.
 #   0: package installed ok
 #   >0: unable to install package
 #######################################
-cnt64_bashlib64_install() {
+function cnt64_bashlib64_install() {
   file_name='bashlib64.bash'
 
   echo "Task: prepare destination (${CNT64_BASHLIB64_TARGET})"
-  if test ! -d "$CNT64_BASHLIB64_TARGET"; then
+  if [[ ! -d "$CNT64_BASHLIB64_TARGET" ]]; then
     mkdir "$CNT64_BASHLIB64_TARGET" &&
       chmod 755 "$CNT64_BASHLIB64_TARGET"
   fi
@@ -69,7 +69,7 @@ cnt64_bashlib64_install() {
   *) return 1 ;;
   esac
 
-  test -f "$file_name" && chmod 644 "$file_name"
+  [[ -f "$file_name" ]] && chmod 644 "$file_name"
 }
 
 #######################################
@@ -83,7 +83,7 @@ cnt64_bashlib64_install() {
 #   0: initialization ok
 #   >: failed to initialize
 #######################################
-cnt64_bashlib64_initialize() {
+function cnt64_bashlib64_initialize() {
   if command -v 'curl' >/dev/null 2>&1; then
     cnt64_bashlib64_download_tool='curl'
   elif command -v 'wget' >/dev/null 2>&1; then
@@ -98,16 +98,16 @@ cnt64_bashlib64_initialize() {
 # Main
 #
 
-cnt64_bashlib64_task_title='Install application: BashLib64'
-cnt64_bashlib64_status=0
-cnt64_bashlib64_download_tool='none'
+declare cnt64_bashlib64_task_title='Install application: BashLib64'
+declare -i cnt64_bashlib64_status=0
+declare cnt64_bashlib64_download_tool='none'
 
 echo "Process: [${cnt64_bashlib64_task_title}] started"
 
-test -n "$CNT64_DEBUG" && set -x
+[[ -n "$CNT64_DEBUG" ]] && set -x
 cnt64_bashlib64_initialize &&
   cnt64_bashlib64_install
 cnt64_bashlib64_status=$?
 
-test "$cnt64_bashlib64_status" -eq 0 && echo "Process: [${cnt64_bashlib64_task_title}] finished successfully" || echo "Process: [${cnt64_bashlib64_task_title}] finished with errors: exit-status-${cnt64_bashlib64_status}"
+((cnt64_bashlib64_status == 0)) && echo "Process: [${cnt64_bashlib64_task_title}] finished successfully" || echo "Process: [${cnt64_bashlib64_task_title}] finished with errors: exit-status-${cnt64_bashlib64_status}"
 exit $cnt64_bashlib64_status
