feat: add ub-23.10, fed39 (#38)

diff --git a/src/helpers/toolbox-k8s/setup b/src/helpers/toolbox-k8s/setup
--- a/src/helpers/toolbox-k8s/setup
+++ b/src/helpers/toolbox-k8s/setup
@@ -28,12 +28,12 @@
 #
 
 # Environment Definition. See docs/base-environment.md for details
-export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
+export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
 export CNT64_DEBUG="${CNT64_DEBUG:-}"
 export CNT64_USER
 
 # shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
-source "$CNT64_BASHLIB64" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
