doc: update

diff --git a/docs/skeletons/helper-setup/setup b/docs/skeletons/helper-setup/setup
--- a/docs/skeletons/helper-setup/setup
+++ b/docs/skeletons/helper-setup/setup
@@ -31,22 +31,22 @@
 export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
 export CNT64_DEBUG="${CNT64_DEBUG:-}"
 export CNT64_USER="${CNT64_USER:-}"
-# X_CODE_PLACEHOLDER_4_X
 
-# shellcheck source=SCRIPTDIR/../../lib/bashlib64.bash
-source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+# source-path=lib/bl64
+# X_IMPORTS_PLACEHOLDER_X
+source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
 #
 
-# X_CODE_PLACEHOLDER_5_X
+# X_GLOBALS_PLACEHOLDER_X
 
 #
 # Functions
 #
 
-# X_CODE_PLACEHOLDER_3_X
+# X_FUNCIONS_PLACEHOLDER_X
 
 #######################################
 # Initialize environment
@@ -79,6 +79,6 @@ bl64_msg_show_batch_start "$cnt64_setup_installer_description"
 
 [[ -n "$CNT64_DEBUG" ]] && bl64_dbg_all_enable
 cnt64_setup_initialize &&
-# X_CODE_PLACEHOLDER_1_X
+# X_MAIN_PLACEHOLDER_X
 
 bl64_msg_show_batch_finish $? "$cnt64_setup_installer_description"
