refact: optimize code

diff --git a/src/helpers/dev/setup b/src/helpers/dev/setup
--- a/src/helpers/dev/setup
+++ b/src/helpers/dev/setup
@@ -5,7 +5,7 @@
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/container64
-# Version: 3.0.0
+# Version: 3.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -32,8 +32,19 @@ export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
 export CNT64_DEBUG="${CNT64_DEBUG:-}"
 export CNT64_USER="${CNT64_USER:-}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+# shellcheck source-path=lib/bl64
+source "${CNT64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rbac.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
@@ -124,6 +135,7 @@ function cnt64_setup_initialize() {
     "${BL64_OS_UB}-22" &&
     bl64_check_export 'CNT64_USER' &&
     bl64_check_privilege_root &&
+    bl64_cryp_setup &&
     bl64_pkg_setup
 }
 
