feat: add gpg (#78)

diff --git a/src/helpers/ansible-test/setup b/src/helpers/ansible-test/setup
--- a/src/helpers/ansible-test/setup
+++ b/src/helpers/ansible-test/setup
@@ -5,7 +5,7 @@
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/container64
-# Version: 2.1.0
+# Version: 2.3.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -30,10 +30,20 @@
 # Environment Definition. See docs/base-environment.md for details
 export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
 export CNT64_DEBUG="${CNT64_DEBUG:-}"
-export CNT64_USER
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+# shellcheck source-path=lib/bl64
+source "${CNT64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rbac.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
@@ -180,21 +190,16 @@ function cnt64_setup_select_packages() {
     packages="${packages} systemd systemd-libs systemd-pam systemd-udev"
     packages="${packages} python3-pip python3-setuptools"
     packages="${packages} python3"
-  elif bl64_os_match "${BL64_OS_UB}-20.4"; then
+  elif bl64_os_match "${BL64_OS_UB}-20"; then
     packages="${packages} dbus dmsetup gir1.2-glib-2.0 networkd-dispatcher shared-mime-info tzdata xdg-user-dirs locales"
     packages="${packages} systemd systemd-timesyncd"
     packages="${packages} file mime-support readline-common xz-utils"
     packages="${packages} python3 python3-dbus python3-gi python3-minimal python3.8 python3.8-minimal python3-pip"
-  elif bl64_os_match "${BL64_OS_UB}-21.4"; then
+  elif bl64_os_match "${BL64_OS_UB}-21" "${BL64_OS_UB}-22"; then
     packages="${packages} dbus dmsetup gir1.2-glib-2.0 networkd-dispatcher shared-mime-info xdg-user-dirs locales"
     packages="${packages} systemd systemd-timesyncd"
     packages="${packages} media-types readline-common tzdata"
     packages="${packages} python3 python3-minimal python3-dbus python3-gi python3-pip"
-  elif bl64_os_match "${BL64_OS_UB}-22.4"; then
-    packages="${packages} dbus dmsetup gir1.2-glib-2.0 networkd-dispatcher shared-mime-info xdg-user-dirs locales"
-    packages="${packages} systemd systemd-timesyncd"
-    packages="${packages} media-types readline-common tzdata"
-    packages="${packages} python3 python3-minimal python3.9 python3-dbus python3-gi python3-pip"
   fi
   [[ -n "$packages" ]] && echo "$packages"
 }
@@ -208,6 +213,13 @@ function cnt64_setup_install_packages() {
     return $?
   # shellcheck disable=SC2086
   bl64_pkg_deploy $packages
+}
+
+function cnt64_setup_install_applications() {
+  bl64_dbg_app_show_function
+  export INST64_ANSIBLE_PIPX='OFF'
+  "${CNT64_INSTALLER_ROOT}/install-go" &&
+    sudo -E -H -u "$CNT64_USER" "${CNT64_INSTALLER_ROOT}/install-ansible"
 }
 
 #######################################
@@ -240,7 +252,9 @@ function cnt64_setup_initialize() {
     "${BL64_OS_RCK}-8" \
     "${BL64_OS_UB}-20.4" "${BL64_OS_UB}-21.4" "${BL64_OS_UB}-22.4" &&
     bl64_check_export 'CNT64_USER' &&
+    bl64_check_export 'CNT64_INSTALLER_ROOT' &&
     bl64_check_privilege_root &&
+    bl64_cryp_setup &&
     bl64_pkg_setup
 }
 
@@ -258,5 +272,6 @@ cnt64_setup_initialize &&
   cnt64_setup_install_packages &&
   cnt64_setup_configure_os &&
   cnt64_setup_create_users &&
-  cnt64_setup_configure_users
+  cnt64_setup_configure_users &&
+  cnt64_setup_install_applications
 bl64_msg_show_batch_finish $? "$cnt64_setup_installer_description"
diff --git a/src/helpers/bash-test/setup b/src/helpers/bash-test/setup
--- a/src/helpers/bash-test/setup
+++ b/src/helpers/bash-test/setup
@@ -5,7 +5,7 @@
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/container64
-# Version: 1.6.0
+# Version: 1.8.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -32,8 +32,19 @@ export CNT64_BASHLIB64="${CNT64_BASHLIB64:-/opt/bl64}"
 export CNT64_DEBUG="${CNT64_DEBUG:-}"
 export CNT64_USER
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+# shellcheck source-path=lib/bl64
+source "${CNT64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rbac.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
@@ -47,25 +58,25 @@ function cnt64_setup_select_packages() {
   bl64_dbg_app_show_function
   local packages=''
   if bl64_os_match "${BL64_OS_ALP}"; then
-    packages='git mawk python3 py3-pip musl musl-utils musl-locales tzdata gettext jq'
+    packages='git mawk python3 py3-pip musl musl-utils musl-locales tzdata gettext jq gpg'
   elif bl64_os_match "${BL64_OS_ALM}"; then
-    packages='git diffutils python3 python3-pip python3-setuptools unzip wget gettext jq'
+    packages='git diffutils python3 python3-pip python3-setuptools unzip wget gettext jq gpg'
   elif bl64_os_match "${BL64_OS_CNT}"; then
-    packages='git diffutils hostname wget python3 python3-pip python3-setuptools unzip gettext jq'
+    packages='git diffutils hostname wget python3 python3-pip python3-setuptools unzip gettext jq gpg'
   elif bl64_os_match "${BL64_OS_DEB}"; then
-    packages='git wget gawk python3 python3-pip python3-venv unzip gettext jq'
+    packages='git wget gawk python3 python3-pip python3-venv unzip gettext jq gpg'
   elif bl64_os_match "${BL64_OS_FD}"; then
-    packages='git diffutils hostname wget python3-pip findutils unzip gettext jq'
+    packages='git diffutils hostname wget python3-pip findutils unzip gettext jq gpg'
   elif bl64_os_match "${BL64_OS_OL}"; then
-    packages='git tar hostname wget python3 python3-pip python3-setuptools unzip gettext jq'
+    packages='git tar hostname wget python3 python3-pip python3-setuptools unzip gettext jq gpg'
   elif bl64_os_match "${BL64_OS_RHEL}"; then
-    packages='git hostname diffutils wget python3 python3-pip python3-setuptools unzip gettext jq'
+    packages='git hostname diffutils wget python3 python3-pip python3-setuptools unzip gettext jq gpg'
   elif bl64_os_match "${BL64_OS_RCK}"; then
-    packages='git hostname diffutils wget python3 python3-pip python3-setuptools findutils unzip gettext jq'
+    packages='git hostname diffutils wget python3 python3-pip python3-setuptools findutils unzip gettext jq gpg'
   elif bl64_os_match "${BL64_OS_SLES}"; then
-    packages='git hostname wget gawk gettext-runtime python3 python3-pip unzip tar jq'
+    packages='git hostname wget gawk gettext-runtime python3 python3-pip unzip tar jq gpg'
   elif bl64_os_match "${BL64_OS_UB}"; then
-    packages='git wget gawk python3 python3-pip python3-venv unzip gettext jq'
+    packages='git wget gawk python3 python3-pip python3-venv unzip gettext jq gpg'
   fi
   [[ -n "$packages" ]] && echo "$packages"
 }
@@ -176,6 +187,7 @@ function cnt64_setup_initialize() {
     "${BL64_OS_UB}" &&
     bl64_check_export 'CNT64_USER' &&
     bl64_check_privilege_root &&
+    bl64_cryp_setup &&
     bl64_pkg_setup
 }
 
diff --git a/src/helpers/bootstrap/bootstrap b/src/helpers/bootstrap/bootstrap
--- a/src/helpers/bootstrap/bootstrap
+++ b/src/helpers/bootstrap/bootstrap
@@ -5,7 +5,7 @@
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/container64
-# Version: 2.4.0
+# Version: 2.5.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -36,8 +36,19 @@ export CNT64_LOCAL_BIN="${CNT64_LOCAL_BIN:-}"
 export CNT64_INSTALLER_ROOT="${CNT64_INSTALLER_ROOT:-}"
 export CNT64_OPT_ROOT="${CNT64_OPT_ROOT:-}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${CNT64_BASHLIB64}/bashlib64.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
+# shellcheck source-path=lib/bl64
+source "${CNT64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-rbac.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${CNT64_BASHLIB64}/bashlib64-core.bash" || { echo "Error: unable to load bashlib64 (${CNT64_BASHLIB64})" && exit 1; }
 
 #
 # Globals
@@ -239,6 +250,7 @@ function cnt64_bootstrap_initialize() {
     bl64_check_export 'CNT64_LOCAL_ROOT' &&
     bl64_check_export 'CNT64_LOCAL_BIN' &&
     bl64_check_export 'CNT64_OPT_ROOT' &&
+    bl64_cryp_setup &&
     bl64_pkg_setup &&
     bl64_check_privilege_root
 }
